/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.awt.Color;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.JSType.isNumber;
import lk.ijse.rmi.cab.controller.InsuaranceCompanyController;
import lk.ijse.rmi.cab.controller.ReservationController;
import lk.ijse.rmi.cab.dto.CustomerDTO;
import lk.ijse.rmi.cab.dto.InsuaranceCompanyDTO;
import lk.ijse.rmi.cab.dto.ReservationDTO;
import lk.ijse.rmi.cab.dto.VehicleDTO;
import lk.ijse.rmi.cab.observer.Observer;

/**
 *
 * @author user
 */
public class AddNewCustomer extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form AddNewCustomer
     */
    public AddNewCustomer() throws RemoteException{
        try {
            initComponents();
            UnicastRemoteObject.exportObject(this,0);
            ReservationController.registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(AddNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    AddNewCustomer(int vehicleId, String startDate, String endDate, Double price, String vehicleBrand, String vehicleInsuaranceId, String vehicleRegNumber, String vehiclcolour, int vehicleSeatingCapacity, String vehicleFuelType, String vehicleStatus, String vehicleInsuaranceCompanyID, Double vehiclePrice, String vehicleInsuaranceCompanyName, String vehicleInsuaranceCompanyType) {
        initComponents();
        btnPayment.setEnabled(false);
        this.txtVehicleId.setText(vehicleId+"");
        this.txtStartDate.setText(startDate);
        this.txtEndDate.setText(endDate);
        this.txtPrice.setText(price+"");
        
        this.txtVehicleBrand.setText(vehicleBrand);
        this.txtVehicleInsuaranceId.setText(vehicleInsuaranceId);
        this.txtVehicleRegNo.setText(vehicleRegNumber);
        this.txtVehicleColour.setText(vehiclcolour);
        this.txtVehicleSeatingCapacity.setText(vehicleSeatingCapacity+"");
        this.txtVehicleFuelType.setText(vehicleFuelType);
        this.txtVehicleStatus.setText(vehicleStatus);
        this.txtVehiclePrice.setText(vehiclePrice.toString());
        this.txtVehicleInsuaranceCompanyId1.setText(vehicleInsuaranceCompanyID);
        this.txtInsuaranceCompanyName.setText(vehicleInsuaranceCompanyName);
        this.txtInsuaranceCompanyType.setText(vehicleInsuaranceCompanyType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCustNicNumber = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtCustDOB = new javax.swing.JTextField();
        txtCustTelNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        txtVehicleBrand = new javax.swing.JTextField();
        txtVehicleInsuaranceId = new javax.swing.JTextField();
        txtVehicleSeatingCapacity = new javax.swing.JTextField();
        txtVehicleFuelType = new javax.swing.JTextField();
        txtVehicleColour = new javax.swing.JTextField();
        txtVehicleRegNo = new javax.swing.JTextField();
        txtVehiclePrice = new javax.swing.JTextField();
        txtVehicleStatus = new javax.swing.JTextField();
        txtInsuaranceCompanyType = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCustomerLicenceId = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtVehicleInsuaranceCompanyId1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtInsuaranceCompanyName = new javax.swing.JTextField();
        btnReseve = new javax.swing.JButton();
        txtReservationId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(150, 40, 27));
        setMinimumSize(new java.awt.Dimension(1530, 847));
        setPreferredSize(new java.awt.Dimension(1564, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Add New Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Customer Details");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("NIC_Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Cust_Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Cust_DOB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Cust_Licence_Id");

        txtCustNicNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustNicNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNicNumberActionPerformed(evt);
            }
        });

        txtCustName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustDOB.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustTelNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Vehicle Details");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Reservation_Id");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Price");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("End_Date");

        txtStartDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtEndDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("     Reseve Detail");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setRequestFocusEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Vehicle _ID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Vehicle_Insurance_ID");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("Vehicle_Reg_No");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setText("Vehicle_Seating_Capaciy ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 255));
        jLabel17.setText("Vehicle_Brand");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Vehicle _FuelType");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Vehicle _Status");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 255));
        jLabel20.setText("Vehicle_Price");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Insurnce_company_Type");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Vehicle_Colour");

        txtVehicleId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleBrand.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleInsuaranceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleSeatingCapacity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtVehicleFuelType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleColour.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleRegNo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehiclePrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehiclePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiclePriceActionPerformed(evt);
            }
        });

        txtVehicleStatus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtInsuaranceCompanyType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtInsuaranceCompanyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuaranceCompanyTypeActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("Cust_Tel_Num");

        txtCustomerLicenceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(51, 51, 255));
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/payment.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 255));
        jLabel24.setText(" Vehicle_Insrnce_Company_Id");

        txtVehicleInsuaranceCompanyId1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehicleInsuaranceCompanyId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleInsuaranceCompanyId1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 255));
        jLabel25.setText("Insurnce_company_Name");

        txtInsuaranceCompanyName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btnReseve.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReseve.setForeground(new java.awt.Color(51, 51, 255));
        btnReseve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/reservation.png"))); // NOI18N
        btnReseve.setText("Reseve Now");
        btnReseve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReseveMouseClicked(evt);
            }
        });
        btnReseve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseveActionPerformed(evt);
            }
        });

        txtReservationId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtReservationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationIdActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 255));
        jLabel26.setText("Start _Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtCustDOB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtCustTelNumber)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReseve)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCustomerLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtPrice))))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtVehicleSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleInsuaranceCompanyId1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVehicleInsuaranceId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtInsuaranceCompanyType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(508, 508, 508)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVehicleInsuaranceCompanyId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleInsuaranceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtInsuaranceCompanyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCustomerLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReseve)
                            .addComponent(btnPayment))
                        .addGap(98, 98, 98))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNicNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNicNumberActionPerformed
        String nic=txtCustNicNumber.getText();
        if (nic.matches("[0-9]{9}[vV]")){
            //JOptionPane.showMessageDialog(this, "Valid NIC");
        }else{
            JOptionPane.showMessageDialog(this, "Invalid NIC");
        }
    }//GEN-LAST:event_txtCustNicNumberActionPerformed

    private void txtVehiclePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiclePriceActionPerformed

    }//GEN-LAST:event_txtVehiclePriceActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
//        String ReservationId=txtReservationId.getText();
//        //double price=Double.parseDouble(txtPrice.getText());
//        int vehicleId=Integer.parseInt(txtVehicleId.getText());
//        //String date = txtStartDate.getText();
//        String checkIn = txtStartDate.getText();
//        String checkOut = txtEndDate.getText();
//        AdvancePaymentForm advancePaymentForm=new AdvancePaymentForm(ReservationId,vehicleId,checkIn,checkOut);

        String ReservationId=txtReservationId.getText();
        String checkIn = txtStartDate.getText();
        String checkOut = txtEndDate.getText();
        //String custId=txtCustId.getText()+"";
        int vehicleId=Integer.parseInt(txtVehicleId.getText());
        
        String custName=txtCustName.getText();
        String custNic=txtCustNicNumber.getText();
        String custLicenId=txtCustomerLicenceId.getText();
        String custTel=txtCustTelNumber.getText();
        String custDOB=txtCustDOB.getText();
        
        String vehicleBrand=txtVehicleBrand.getText();
        String vehicleInsuaranceId=txtVehicleInsuaranceId.getText();
        String vehicleRegNumber=txtVehicleRegNo.getText();
        String vehiclcolour=txtVehicleColour.getText();
        int vehicleSeatingCapacity=Integer.parseInt(txtVehicleSeatingCapacity.getText());
        String vehicleFuelType=txtVehicleFuelType.getText();
        String vehicleStatus=txtVehicleStatus.getText();
        Double vehiclePrice=Double.parseDouble(txtVehiclePrice.getText());
        String vehicleInsuaranceCompanyID=txtVehicleInsuaranceCompanyId1.getText();
        String vehicleInsuaranceCompanyName=txtInsuaranceCompanyName.getText();
        String vehicleInsuaranceCompanyType=txtInsuaranceCompanyType.getText();
        
        AdvancePaymentForm advancePaymentForm=new AdvancePaymentForm(ReservationId, checkIn,checkOut,vehicleId,custName,custNic,custLicenId,
        custTel,custDOB,vehicleBrand,vehicleInsuaranceId,vehicleRegNumber,vehiclcolour,vehicleSeatingCapacity,vehicleFuelType,
        vehicleStatus,vehiclePrice,vehicleInsuaranceCompanyID,vehicleInsuaranceCompanyName,vehicleInsuaranceCompanyType);
        
        advancePaymentForm.setSize(this.getSize());
        this.removeAll();
        this.add(advancePaymentForm);
        this.repaint();
        this.revalidate();
        advancePaymentForm.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void txtVehicleInsuaranceCompanyId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleInsuaranceCompanyId1ActionPerformed
        try {
            String id=txtVehicleInsuaranceCompanyId1.getText();
            InsuaranceCompanyDTO insuaranceCompanyDTO=InsuaranceCompanyController.searchById(id);
            if(insuaranceCompanyDTO!=null){
                txtInsuaranceCompanyName.setText(insuaranceCompanyDTO.getCompanyName());
                txtInsuaranceCompanyType.setText(insuaranceCompanyDTO.getInsuaranceType());
            }
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtVehicleInsuaranceCompanyId1ActionPerformed

    private void btnReseveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReseveMouseClicked

    }//GEN-LAST:event_btnReseveMouseClicked

    private void btnReseveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReseveActionPerformed
        String nic=txtCustNicNumber.getText();
        if (nic.matches("[0-9]{9}[vV]")){
            String tel=txtCustTelNumber.getText();
            if (!isValidTP(tel)){
            JOptionPane.showMessageDialog(this, "Please enter a valid telephone number");
            txtCustTelNumber.selectAll();
            txtCustTelNumber.requestFocusInWindow();
            return;
            }
            //JOptionPane.showMessageDialog(this, "Valid NIC");
        
        try {
            VehicleDTO vehicleDTO=new VehicleDTO();
            vehicleDTO.setVehicleId(Integer.parseInt(txtVehicleId.getText()));
            vehicleDTO.setVehicleBrand(txtVehicleBrand.getText());
            vehicleDTO.setVehicleInsuaranceId(txtVehicleInsuaranceId.getText());
            vehicleDTO.setRegNo(txtVehicleRegNo.getText());
            vehicleDTO.setColour(txtVehicleColour.getText());
            vehicleDTO.setSeatingCapacity(Integer.parseInt(txtVehicleSeatingCapacity.getText()));
            vehicleDTO.setFuelType(txtVehicleFuelType.getText());
            vehicleDTO.setStatus(txtVehicleStatus.getText());
            vehicleDTO.setPrice(Double.parseDouble(txtVehiclePrice.getText()));
            
            InsuaranceCompanyDTO insuaranceCompanyDTO=new InsuaranceCompanyDTO();
            insuaranceCompanyDTO.setInsuaranceCompanyId(txtVehicleInsuaranceCompanyId1.getText());
            insuaranceCompanyDTO.setCompanyName(txtInsuaranceCompanyName.getText());
            insuaranceCompanyDTO.setInsuaranceType(txtInsuaranceCompanyType.getText());
            vehicleDTO.setInsuaranceCompanyDTO(insuaranceCompanyDTO);
            
            CustomerDTO customerDTO=new CustomerDTO();
            customerDTO.setCustName(txtCustName.getText());
            customerDTO.setCustNic(txtCustNicNumber.getText());
            customerDTO.setCustLicenseId(txtCustomerLicenceId.getText());
            customerDTO.setCustTelNumber(txtCustTelNumber.getText());
            customerDTO.setCustDob(txtCustDOB.getText());
            
            ReservationDTO reservationDTO=new ReservationDTO();
            reservationDTO.setReseveId(txtReservationId.getText());
            reservationDTO.setStartDate(txtStartDate.getText());
            reservationDTO.setEndDate(txtEndDate.getText());
            reservationDTO.setPrice(Double.parseDouble(txtPrice.getText()));
            reservationDTO.setCustomerDTO(customerDTO);
            reservationDTO.setVehicleDTO(vehicleDTO);
            
            boolean isAdded=ReservationController.addReservation(reservationDTO);
            if(isAdded){
                JOptionPane.showMessageDialog(this,"Added");
                btnPayment.setEnabled(true);
                
                btnPayment.setForeground(Color.green);
                btnPayment.setText("press Payment Button");
            }else{
                JOptionPane.showMessageDialog(this,"Not Added");
                  //JOptionPane.showMessageDialog(this, "Please Fill Press Reseve Button");
                btnPayment.setForeground(Color.red);
                btnPayment.setText("Wrong Data");
                btnPayment.setEnabled(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
                
         }else{
             JOptionPane.showMessageDialog(this,"Invalid nic");
         }
    }//GEN-LAST:event_btnReseveActionPerformed

    private void txtReservationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationIdActionPerformed

    private void txtInsuaranceCompanyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuaranceCompanyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuaranceCompanyTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnReseve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCustDOB;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustNicNumber;
    private javax.swing.JTextField txtCustTelNumber;
    private javax.swing.JTextField txtCustomerLicenceId;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtInsuaranceCompanyName;
    private javax.swing.JTextField txtInsuaranceCompanyType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReservationId;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtVehicleBrand;
    private javax.swing.JTextField txtVehicleColour;
    private javax.swing.JTextField txtVehicleFuelType;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtVehicleInsuaranceCompanyId1;
    private javax.swing.JTextField txtVehicleInsuaranceId;
    private javax.swing.JTextField txtVehiclePrice;
    private javax.swing.JTextField txtVehicleRegNo;
    private javax.swing.JTextField txtVehicleSeatingCapacity;
    private javax.swing.JTextField txtVehicleStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String message) throws Exception {
        JOptionPane.showMessageDialog(this, message);
    }

    private boolean isValidTP(String tel) {
        if (tel.length() == 11){
            
            String dash = tel.substring(3, 4);
            
            if (dash.equals("-")){
                
                tel = tel.replace("-", "");
                
                if (isNumber(tel)){
                    return true;
                }
                
            }
            
        }
        
        return false;
    }
}
