/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.rmi.cab.controller.paymentController;
import lk.ijse.rmi.cab.dto.PaymentDTO;

/**
 *
 * @author user
 */
public class FullPayment extends javax.swing.JPanel {

    /**
     * Creates new form FullPayment
     */
    public FullPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelpaymentdetail = new javax.swing.JLabel();
        labelreservationid = new javax.swing.JLabel();
        labelroomid = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        labeltime = new javax.swing.JLabel();
        labelfullamount = new javax.swing.JLabel();
        btnprintbill = new javax.swing.JButton();
        txtTime = new javax.swing.JTextField();
        txtCustId = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtFullAmount = new javax.swing.JTextField();
        labelpaymentid1 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        labelguest1 = new javax.swing.JLabel();
        txtReservationId = new javax.swing.JTextField();
        labelsettlefullpayment = new javax.swing.JLabel();
        Text_Arrears = new javax.swing.JTextField();
        labeladvance = new javax.swing.JLabel();
        txtAdvance = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtPaymentId = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(150, 40, 27));

        labelpaymentdetail.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelpaymentdetail.setForeground(new java.awt.Color(51, 0, 255));
        labelpaymentdetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/payment.png"))); // NOI18N
        labelpaymentdetail.setText("   Full Payment Detail & Print Bill");

        labelreservationid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid.setText("Reservation Id");

        labelroomid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelroomid.setForeground(new java.awt.Color(102, 102, 255));
        labelroomid.setText("Vehicle_Id");

        labeldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeldate.setForeground(new java.awt.Color(102, 102, 255));
        labeldate.setText("Date");

        labeltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeltime.setForeground(new java.awt.Color(102, 102, 255));
        labeltime.setText("Time");

        labelfullamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelfullamount.setForeground(new java.awt.Color(102, 102, 255));
        labelfullamount.setText("Full Amount");

        btnprintbill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnprintbill.setForeground(new java.awt.Color(102, 102, 255));
        btnprintbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/bill.png"))); // NOI18N
        btnprintbill.setText("Print Bill");
        btnprintbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintbillMouseClicked(evt);
            }
        });

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtTime.setBorder(null);
        txtTime.setOpaque(false);

        txtCustId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustId.setBorder(null);
        txtCustId.setOpaque(false);

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtDate.setBorder(null);
        txtDate.setOpaque(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtFullAmount.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtFullAmount.setBorder(null);
        txtFullAmount.setOpaque(false);
        txtFullAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullAmountActionPerformed(evt);
            }
        });

        labelpaymentid1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelpaymentid1.setForeground(new java.awt.Color(102, 102, 255));
        labelpaymentid1.setText("Payment Id");

        txtVehicleId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehicleId.setBorder(null);
        txtVehicleId.setOpaque(false);

        labelguest1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguest1.setForeground(new java.awt.Color(102, 102, 255));
        labelguest1.setText("Cust_Id");

        txtReservationId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtReservationId.setBorder(null);
        txtReservationId.setOpaque(false);
        txtReservationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationIdActionPerformed(evt);
            }
        });

        labelsettlefullpayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelsettlefullpayment.setForeground(new java.awt.Color(102, 102, 255));
        labelsettlefullpayment.setText("Arrears");

        Text_Arrears.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Text_Arrears.setBorder(null);
        Text_Arrears.setOpaque(false);
        Text_Arrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_ArrearsActionPerformed(evt);
            }
        });

        labeladvance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeladvance.setForeground(new java.awt.Color(102, 102, 255));
        labeladvance.setText("Advance");

        txtAdvance.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtAdvance.setBorder(null);
        txtAdvance.setOpaque(false);
        txtAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvanceActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        txtPaymentId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtPaymentId.setBorder(null);
        txtPaymentId.setOpaque(false);
        txtPaymentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIdActionPerformed(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelpaymentid1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelreservationid))
                                        .addGap(91, 91, 91))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelguest1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(118, 118, 118)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5)
                                    .addComponent(jSeparator4)
                                    .addComponent(jSeparator3)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator1)
                                    .addComponent(txtTime)
                                    .addComponent(txtCustId)
                                    .addComponent(txtVehicleId)
                                    .addComponent(txtDate)
                                    .addComponent(txtReservationId)
                                    .addComponent(txtPaymentId, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeladvance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfullamount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelsettlefullpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator8)
                                .addComponent(txtFullAmount)
                                .addComponent(Text_Arrears)
                                .addComponent(txtAdvance)
                                .addComponent(jSeparator6)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnprintbill)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(labelpaymentdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelpaymentdetail)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelpaymentid1)
                            .addComponent(txtPaymentId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustId)
                            .addComponent(labelguest1))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelroomid)
                            .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeldate)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeltime)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfullamount))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAdvance, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeladvance, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsettlefullpayment)
                            .addComponent(Text_Arrears, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprintbill))
                .addGap(155, 155, 155))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnprintbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintbillMouseClicked

    }//GEN-LAST:event_btnprintbillMouseClicked

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtFullAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullAmountActionPerformed
        txtAdvance.requestFocus();
    }//GEN-LAST:event_txtFullAmountActionPerformed

    private void txtReservationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationIdActionPerformed

    private void Text_ArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_ArrearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_ArrearsActionPerformed

    private void txtAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvanceActionPerformed
        double amount=Double.parseDouble(txtFullAmount.getText());
        double addvance=Double.parseDouble(txtAdvance.getText());
        double arreas=amount-addvance;
        Text_Arrears.setText(""+arreas);
    }//GEN-LAST:event_txtAdvanceActionPerformed

    private void txtPaymentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIdActionPerformed
        try {
            int paymentId=Integer.parseInt(txtPaymentId.getText());
            PaymentDTO paymentDTO=paymentController.findDetailsforFullPayment(paymentId);
            if(paymentDTO!=null){
                txtReservationId.setText(paymentDTO.getReservationDTO().getReseveId());
                txtTime.setText(paymentDTO.getTime());
                txtFullAmount.setText(paymentDTO.getAmmountPaid()+"");
                txtDate.setText(paymentDTO.getDate());
                txtCustId.setText(paymentDTO.getReservationDTO().getCustomerDTO().getCustId()+"");
                txtVehicleId.setText(paymentDTO.getReservationDTO().getVehicleDTO().getVehicleId()+"");
                txtAdvance.setText(paymentDTO.getAdvance()+"");
            }
        } catch (Exception ex) {
            Logger.getLogger(FullPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPaymentIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Arrears;
    private javax.swing.JButton btnprintbill;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labeladvance;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labelfullamount;
    private javax.swing.JLabel labelguest1;
    private javax.swing.JLabel labelpaymentdetail;
    private javax.swing.JLabel labelpaymentid1;
    private javax.swing.JLabel labelreservationid;
    private javax.swing.JLabel labelroomid;
    private javax.swing.JLabel labelsettlefullpayment;
    private javax.swing.JLabel labeltime;
    private javax.swing.JTextField txtAdvance;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFullAmount;
    private javax.swing.JTextField txtPaymentId;
    private javax.swing.JTextField txtReservationId;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables
}
