/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainnForm
     */
    public MainForm() {
        initComponents();
        loadDate();
        loadTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        reservationlabel = new javax.swing.JLabel();
        viewroomlabel = new javax.swing.JLabel();
        viewpaymentlabel = new javax.swing.JLabel();
        viewresevedetaillabel = new javax.swing.JLabel();
        modifyreservatinlabel = new javax.swing.JLabel();
        modifyroomlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        desktopPanel1 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lableTime = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        jPanel2.setForeground(new java.awt.Color(34, 49, 63));

        reservationlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reservationlabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        reservationlabel.setText("   Reservation");
        reservationlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservationlabelMouseEntered(evt);
            }
        });

        viewroomlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewroomlabel.setForeground(new java.awt.Color(255, 255, 255));
        viewroomlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        viewroomlabel.setText("   View Vehicles");
        viewroomlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewroomlabelMouseClicked(evt);
            }
        });

        viewpaymentlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewpaymentlabel.setForeground(new java.awt.Color(255, 255, 255));
        viewpaymentlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        viewpaymentlabel.setText("   View Payment");
        viewpaymentlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewpaymentlabelMouseClicked(evt);
            }
        });

        viewresevedetaillabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewresevedetaillabel.setForeground(new java.awt.Color(255, 255, 255));
        viewresevedetaillabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        viewresevedetaillabel.setText("   View Reserve Detail");
        viewresevedetaillabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewresevedetaillabelMouseClicked(evt);
            }
        });

        modifyreservatinlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modifyreservatinlabel.setForeground(new java.awt.Color(255, 255, 255));
        modifyreservatinlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        modifyreservatinlabel.setText("   Modify Vehicles");
        modifyreservatinlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyreservatinlabelMouseClicked(evt);
            }
        });

        modifyroomlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modifyroomlabel.setForeground(new java.awt.Color(255, 255, 255));
        modifyroomlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        modifyroomlabel.setText("   Modify Customers");
        modifyroomlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyroomlabelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/Folder_32.png"))); // NOI18N
        jLabel7.setText("  Modify Reservation");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewresevedetaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservationlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifyreservatinlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewpaymentlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(viewroomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(modifyroomlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(reservationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewroomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewpaymentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewresevedetaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(modifyreservatinlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(modifyroomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout desktopPanel1Layout = new javax.swing.GroupLayout(desktopPanel1);
        desktopPanel1.setLayout(desktopPanel1Layout);
        desktopPanel1Layout.setHorizontalGroup(
            desktopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1564, Short.MAX_VALUE)
        );
        desktopPanel1Layout.setVerticalGroup(
            desktopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/goToLoginPage.png"))); // NOI18N
        jLabel1.setText("Go To Login Page");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/admin.png"))); // NOI18N
        jLabel2.setText("Well Come To Reciption");

        lableTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lableTime.setForeground(new java.awt.Color(255, 51, 51));
        lableTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/dateTo.png"))); // NOI18N

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelDate.setForeground(new java.awt.Color(255, 51, 51));
        labelDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/time.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/carrent.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopPanel1))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lableTime, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableTime, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktopPanel1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationlabelMouseClicked
                  SelectTheDate selectTheDate=new SelectTheDate();
                  selectTheDate.setSize(desktopPanel1.getSize());
                  desktopPanel1.removeAll();
                  desktopPanel1.add(selectTheDate);
                  desktopPanel1.repaint();
                  desktopPanel1.revalidate();
       
    }//GEN-LAST:event_reservationlabelMouseClicked

    private void reservationlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationlabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationlabelMouseEntered

    private void viewroomlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewroomlabelMouseClicked
                  ViewAllVehicleDetailsFrom v=new ViewAllVehicleDetailsFrom();
                  v.setSize(desktopPanel1.getSize());
                  desktopPanel1.removeAll();
                  desktopPanel1.add(v);
                  desktopPanel1.repaint();
                  desktopPanel1.revalidate();
                  v.setVisible(true);
       
    }//GEN-LAST:event_viewroomlabelMouseClicked

    private void viewpaymentlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpaymentlabelMouseClicked
            FullPayment fullPayment=new FullPayment();
            fullPayment.setSize(desktopPanel1.getSize());
            desktopPanel1.removeAll();
            desktopPanel1.add(fullPayment);
            desktopPanel1.repaint();
            desktopPanel1.revalidate();
            fullPayment.setVisible(true);
                    
            

    }//GEN-LAST:event_viewpaymentlabelMouseClicked

    private void viewresevedetaillabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewresevedetaillabelMouseClicked
            ViewAllReserveDetails v1=new ViewAllReserveDetails();
            v1.setSize(desktopPanel1.getSize());
            desktopPanel1.removeAll();
            desktopPanel1.add(v1);
            desktopPanel1.repaint();
            desktopPanel1.revalidate();
            v1.setVisible(true);
        
               
    }//GEN-LAST:event_viewresevedetaillabelMouseClicked

    private void modifyreservatinlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyreservatinlabelMouseClicked
        
        try {
            ModifyVehicles modifyVehicles=new ModifyVehicles();
            modifyVehicles.setSize(desktopPanel1.getSize());
            desktopPanel1.removeAll();
            desktopPanel1.add(modifyVehicles);
            desktopPanel1.repaint();
            desktopPanel1.revalidate();
            modifyVehicles.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_modifyreservatinlabelMouseClicked

    private void modifyroomlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyroomlabelMouseClicked
        try {
            ModifyCustomer modifyCustomer=new ModifyCustomer();
            modifyCustomer.setSize(desktopPanel1.getSize());
            desktopPanel1.removeAll();
            desktopPanel1.add(modifyCustomer);
            desktopPanel1.repaint();
            desktopPanel1.revalidate();
            modifyCustomer.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_modifyroomlabelMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        SerchVehicleForModifyReservation s=new SerchVehicleForModifyReservation();
        s.setSize(desktopPanel1.getSize());
        desktopPanel1.removeAll();
        desktopPanel1.add(s);
        desktopPanel1.repaint();
        desktopPanel1.revalidate();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       LoginForm l=new LoginForm();
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel lableTime;
    private javax.swing.JLabel modifyreservatinlabel;
    private javax.swing.JLabel modifyroomlabel;
    private javax.swing.JLabel reservationlabel;
    private javax.swing.JLabel viewpaymentlabel;
    private javax.swing.JLabel viewresevedetaillabel;
    private javax.swing.JLabel viewroomlabel;
    // End of variables declaration//GEN-END:variables

    private void loadDate() {
        Date d=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        String date=df.format(d);
        lableTime.setText(date);
    }

    private void loadTime() {
         Timer t=new Timer(0,((e) -> {
            Calendar c=Calendar.getInstance();
            SimpleDateFormat df=new SimpleDateFormat("hh.mm.ss");
            String time=df.format(c.getTime());
            labelDate.setText(time);
        }));
        t.start();
    }
}
