/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.rmi.cab.controller.InsuaranceCompanyController;
import lk.ijse.rmi.cab.controller.VehicleController;
import lk.ijse.rmi.cab.dto.InsuaranceCompanyDTO;
import lk.ijse.rmi.cab.dto.VehicleDTO;
import lk.ijse.rmi.cab.observer.Observer;

/**
 *
 * @author user
 */
public class ModifyVehicles extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form ModifyVehicles
     */
    public ModifyVehicles() throws RemoteException{
        try {
            initComponents();
            
            getAllInsuaranceCompany();
            loadVehicles();
            UnicastRemoteObject.exportObject(this,0);
            VehicleController.registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtVehicleBrand = new javax.swing.JTextField();
        txtVehicleInsuaranceId = new javax.swing.JTextField();
        txtVehcleRegNumber = new javax.swing.JTextField();
        txtVehicleSeatingCapacity = new javax.swing.JTextField();
        txtVehicleFuelType = new javax.swing.JTextField();
        txtVehicleStatus = new javax.swing.JTextField();
        txtVehiclePrice = new javax.swing.JTextField();
        txtVehicleColour = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtInsuaranceCompanyId = new javax.swing.JTextField();
        txtInsuaranceType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVehicles = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        JComboInsuaranceCompanyName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(150, 40, 27));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Modify Vehicle Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Vehicle Brand");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Insuarance Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Register Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Fuel Type");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Vehicle Id");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Status");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Colour");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Price");

        txtVehicleBrand.setEditable(false);
        txtVehicleBrand.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleInsuaranceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehcleRegNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehcleRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehcleRegNumberActionPerformed(evt);
            }
        });

        txtVehicleSeatingCapacity.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleFuelType.setEditable(false);
        txtVehicleFuelType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleStatus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehicleStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleStatusActionPerformed(evt);
            }
        });

        txtVehiclePrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleColour.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Company Register Id");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("Insuarance Type");

        txtInsuaranceCompanyId.setEditable(false);
        txtInsuaranceCompanyId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtInsuaranceCompanyId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuaranceCompanyIdActionPerformed(evt);
            }
        });

        txtInsuaranceType.setEditable(false);
        txtInsuaranceType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setText("Insuarance Company Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setText("Seating Capacity");

        txtVehicleId.setEditable(false);
        txtVehicleId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        tableVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle_Id", "Brand", "Insuarance_ID", "Reg_No", "Colour", "Seating_Capacity", "Fuel Type", "Status", "Price", "InsuaranceCompanyId"
            }
        ));
        tableVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVehicles);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/List.png"))); // NOI18N
        jLabel14.setText("List Of Vehicles");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/updateIcon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/headLine.png"))); // NOI18N

        JComboInsuaranceCompanyName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        JComboInsuaranceCompanyName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboInsuaranceCompanyNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVehicleSeatingCapacity)
                                    .addComponent(txtVehicleInsuaranceId)
                                    .addComponent(txtVehicleFuelType)
                                    .addComponent(txtVehcleRegNumber)
                                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtInsuaranceCompanyId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JComboInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(258, 258, 258)
                                                .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtInsuaranceType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel12))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehcleRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(JComboInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehicleInsuaranceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtInsuaranceCompanyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtInsuaranceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehcleRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehcleRegNumberActionPerformed
        try {
            String regNO=txtVehcleRegNumber.getText();
            VehicleDTO vehicleDTO=VehicleController.getVehicleDetailsForModify(regNO);
            if(vehicleDTO!=null){
                boolean isReseved=VehicleController.reserve(regNO);
                if(isReseved){
                    txtVehicleId.setText(vehicleDTO.getVehicleId()+"");
                    txtVehicleBrand.setText(vehicleDTO.getVehicleBrand());
                    txtVehicleInsuaranceId.setText(vehicleDTO.getVehicleInsuaranceId());
                    txtVehicleColour.setText(vehicleDTO.getColour());
                    txtVehicleSeatingCapacity.setText(vehicleDTO.getSeatingCapacity()+"");
                    txtVehicleFuelType.setText(vehicleDTO.getFuelType());
                    txtVehicleStatus.setText(vehicleDTO.getStatus());
                    txtVehiclePrice.setText(vehicleDTO.getPrice()+"");
                
                    txtInsuaranceCompanyId.setText(vehicleDTO.getInsuaranceCompanyDTO().getInsuaranceCompanyId());
                    JComboInsuaranceCompanyName.setSelectedItem(vehicleDTO.getInsuaranceCompanyDTO().getCompanyName());
                    txtInsuaranceType.setText(vehicleDTO.getInsuaranceCompanyDTO().getInsuaranceType());
                }else{
                    JOptionPane.showMessageDialog(this,"This Vehicle Is While Reserving");
                }
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtVehcleRegNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int vehicleId=Integer.parseInt(txtVehicleId.getText());
            
            boolean isDelete=VehicleController.deleteVehicle(vehicleId);
            if(isDelete){
                VehicleController.release(txtVehcleRegNumber.getText());
                JOptionPane.showMessageDialog(this,"This vehicle is has delete successfully");
            }else{
                JOptionPane.showMessageDialog(this,"This vehicle recived or not delete");
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
           
            
        try {
            VehicleDTO vehicleDTO=new VehicleDTO();
            vehicleDTO.setVehicleId(Integer.parseInt(txtVehicleId.getText()));
            vehicleDTO.setVehicleBrand(txtVehicleBrand.getText());
            vehicleDTO.setVehicleInsuaranceId(txtVehicleInsuaranceId.getText());
            vehicleDTO.setRegNo(txtVehcleRegNumber.getText());
            vehicleDTO.setColour(txtVehicleColour.getText());
            vehicleDTO.setSeatingCapacity(Integer.parseInt(txtVehicleSeatingCapacity.getText()));
            vehicleDTO.setFuelType(txtVehicleFuelType.getText());
            vehicleDTO.setStatus(txtVehicleStatus.getText());
            vehicleDTO.setPrice(Double.parseDouble(txtVehiclePrice.getText()));
            
            InsuaranceCompanyDTO insuaranceCompanyDTO=new InsuaranceCompanyDTO();
            insuaranceCompanyDTO.setInsuaranceCompanyId(txtInsuaranceCompanyId.getText());
            insuaranceCompanyDTO.setCompanyName(JComboInsuaranceCompanyName.getSelectedItem().toString());
            insuaranceCompanyDTO.setInsuaranceType(txtInsuaranceType.getText());
            vehicleDTO.setInsuaranceCompanyDTO(insuaranceCompanyDTO);
            
            boolean isUpdate=VehicleController.updateVehicle(vehicleDTO);
            if(isUpdate){
                VehicleController.release(txtVehcleRegNumber.getText());
                JOptionPane.showMessageDialog(this,"This vehicle has been update successfully");
            }else{
                JOptionPane.showMessageDialog(this,"This vehicle recived or not update");
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVehiclesMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tableVehicles.getModel();
        String regNo=(String) tableVehicles.getValueAt(tableVehicles.getSelectedRow(),3);
        txtVehcleRegNumber.setText(regNo);
        txtVehcleRegNumber.requestFocus();
    }//GEN-LAST:event_tableVehiclesMouseClicked

    private void txtInsuaranceCompanyIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuaranceCompanyIdActionPerformed
        
    }//GEN-LAST:event_txtInsuaranceCompanyIdActionPerformed

    private void JComboInsuaranceCompanyNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboInsuaranceCompanyNameItemStateChanged
        try {
            String companyName=JComboInsuaranceCompanyName.getSelectedItem().toString();
            InsuaranceCompanyDTO insuaranceCompanyDTO=InsuaranceCompanyController.getFindByCompanyName(companyName);
            //this.insuaranceCompanyDTO=insuaranceCompanyDTO;
            if(insuaranceCompanyDTO!=null){
                txtInsuaranceCompanyId.setText(insuaranceCompanyDTO.getInsuaranceCompanyId());
                txtInsuaranceType.setText(insuaranceCompanyDTO.getInsuaranceType());
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JComboInsuaranceCompanyNameItemStateChanged

    private void txtVehicleStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboInsuaranceCompanyName;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVehicles;
    private javax.swing.JTextField txtInsuaranceCompanyId;
    private javax.swing.JTextField txtInsuaranceType;
    private javax.swing.JTextField txtVehcleRegNumber;
    private javax.swing.JTextField txtVehicleBrand;
    private javax.swing.JTextField txtVehicleColour;
    private javax.swing.JTextField txtVehicleFuelType;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtVehicleInsuaranceId;
    private javax.swing.JTextField txtVehiclePrice;
    private javax.swing.JTextField txtVehicleSeatingCapacity;
    private javax.swing.JTextField txtVehicleStatus;
    // End of variables declaration//GEN-END:variables

    private void loadVehicles() {
        try {
            DefaultTableModel dtm=(DefaultTableModel) tableVehicles.getModel();
            dtm.setRowCount(0);
            
            List<VehicleDTO>vehicleDTOs=VehicleController.findAllVehicles();
//            if(vehicleDTOs==null){
//                return;
//            }
            for (VehicleDTO vehicleDTO : vehicleDTOs) {
                Object[] rowDeta={
                    vehicleDTO.getVehicleId(),
                    vehicleDTO.getVehicleBrand(),
                    vehicleDTO.getVehicleInsuaranceId(),
                    vehicleDTO.getRegNo(),
                    vehicleDTO.getColour(),
                    vehicleDTO.getSeatingCapacity(),
                    vehicleDTO.getFuelType(),
                    vehicleDTO.getStatus(),
                    vehicleDTO.getPrice(),
                    vehicleDTO.getInsuaranceCompanyDTO().getInsuaranceCompanyId()
                    
                        
                        
                };
                dtm.addRow(rowDeta);
                tableVehicles.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void getAllInsuaranceCompany() {
        try {
            List<InsuaranceCompanyDTO> insuaranceCompanyDTOs=InsuaranceCompanyController.findAllInsuaranceCompany();
            for (InsuaranceCompanyDTO insuaranceCompanyDTO : insuaranceCompanyDTOs) {
                JComboInsuaranceCompanyName.addItem(insuaranceCompanyDTO.getCompanyName());
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void update(String message) throws Exception {
        JOptionPane.showMessageDialog(this, message);
        loadVehicles();
    }
}
