/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.rmi.cab.controller.CustomerController;
import lk.ijse.rmi.cab.dto.CustomerDTO;
import lk.ijse.rmi.cab.observer.Observer;

/**
 *
 * @author user
 */
public class ModifyCustomer extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form ModifyCustomer
     */
    public ModifyCustomer() throws RemoteException{
        try {
            initComponents();
            loadAllCustomers();
            UnicastRemoteObject.exportObject(this,0);
            CustomerController.registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(ModifyCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCustNicNumber = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtCustTelNum = new javax.swing.JTextField();
        txtCustDOB = new javax.swing.JTextField();
        txtCustLicenceId = new javax.swing.JTextField();
        labelmodifyguestdetail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelmodifyguestdetail1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(150, 40, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Cust_Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Cust_Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Cust_Tel_Num");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Cust_DOB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Cust_Licence_Id");

        txtCustNicNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustNicNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNicNumberActionPerformed(evt);
            }
        });

        txtCustName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });

        txtCustTelNum.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustDOB.setEditable(false);
        txtCustDOB.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustLicenceId.setEditable(false);
        txtCustLicenceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        labelmodifyguestdetail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelmodifyguestdetail.setForeground(new java.awt.Color(255, 51, 102));
        labelmodifyguestdetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/List.png"))); // NOI18N
        labelmodifyguestdetail.setText("List Of Modify Customers");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Cust_NIC_Number");

        txtCustomerId.setEditable(false);
        txtCustomerId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });

        tableCustomer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tableCustomer.setForeground(new java.awt.Color(51, 102, 255));
        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust_ID", "Cust_Name", "Cust_NIC_Number", "Cust_LicenseId", "Cust_Tel_Num", "Cust_DOB"
            }
        ));
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomer);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 102, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/updateIcon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelmodifyguestdetail1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelmodifyguestdetail1.setForeground(new java.awt.Color(51, 0, 204));
        labelmodifyguestdetail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/user.png"))); // NOI18N
        labelmodifyguestdetail1.setText(" Modify Customer Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(labelmodifyguestdetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelmodifyguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelmodifyguestdetail1)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(labelmodifyguestdetail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNicNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNicNumberActionPerformed
        
            
        try {
            String nicNumber=txtCustNicNumber.getText();
            CustomerDTO customerDTO=CustomerController.findBYNicNumber(nicNumber);
            if(customerDTO!=null){
                boolean reserved= CustomerController.customerReseveByNicNumber(nicNumber);
                if(reserved){ 
                    txtCustomerId.setText(customerDTO.getCustId()+"");
                    txtCustName.setText(customerDTO.getCustName());
                    txtCustLicenceId.setText(customerDTO.getCustLicenseId());
                    txtCustDOB.setText(customerDTO.getCustDob());
                    txtCustTelNum.setText(customerDTO.getCustTelNumber());
                }else{
                    JOptionPane.showMessageDialog(this,"This Id Is While Reserving");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                

            
        
    }//GEN-LAST:event_txtCustNicNumberActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void tableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tableCustomer.getModel();
        String custNicNumber=(String) tableCustomer.getValueAt(tableCustomer.getSelectedRow(),2);
        txtCustNicNumber.setText(custNicNumber);
        txtCustNicNumber.requestFocus();
    }//GEN-LAST:event_tableCustomerMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            CustomerDTO customerDTO=new CustomerDTO();
            customerDTO.setCustId(Integer.parseInt(txtCustomerId.getText()));
            customerDTO.setCustName(txtCustName.getText());
            customerDTO.setCustNic(txtCustNicNumber.getText());
            customerDTO.setCustLicenseId(txtCustLicenceId.getText());
            customerDTO.setCustTelNumber(txtCustTelNum.getText());
            customerDTO.setCustDob(txtCustDOB.getText());
            
            boolean isUpdate=CustomerController.updateCustomer(customerDTO);
            if(isUpdate){
                CustomerController.customerReleaseByNicNumber(txtCustNicNumber.getText());
                JOptionPane.showMessageDialog(this,"customer has been update successfully");
            }else{
                JOptionPane.showMessageDialog(this,"This Customer Is Reseved OR Not Update");
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int custId=Integer.parseInt(txtCustomerId.getText());
            boolean isDelete=CustomerController.deleteCustomer(custId);
            if(isDelete){
                CustomerController.customerReleaseByNicNumber(txtCustNicNumber.getText());
                JOptionPane.showMessageDialog(this,"customer has been delete successfully");
            }else{
                JOptionPane.showMessageDialog(this,"This Customer Is Recived OR Not Delete");
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelmodifyguestdetail;
    private javax.swing.JLabel labelmodifyguestdetail1;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtCustDOB;
    private javax.swing.JTextField txtCustLicenceId;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustNicNumber;
    private javax.swing.JTextField txtCustTelNum;
    private javax.swing.JTextField txtCustomerId;
    // End of variables declaration//GEN-END:variables

    private void loadAllCustomers() {
        try {
            DefaultTableModel dtm=(DefaultTableModel) tableCustomer.getModel();
            dtm.setRowCount(0);
            
            List<CustomerDTO>customerDTOs=CustomerController.findAllCustomers();
            
            for (CustomerDTO customerDTO : customerDTOs) {
                Object[]rowData={
                    customerDTO.getCustId(),
                    customerDTO.getCustName(),
                    customerDTO.getCustNic(),
                    customerDTO.getCustLicenseId(),
                    customerDTO.getCustTelNumber(),
                    customerDTO.getCustDob()
                };
                dtm.addRow(rowData);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void update(String message) throws Exception {
       JOptionPane.showMessageDialog(this, message);
       loadAllCustomers();
    }
}
