/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rmi.cab.view;

import java.awt.Color;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.rmi.cab.controller.CustomerController;
import lk.ijse.rmi.cab.controller.InsuaranceCompanyController;
import lk.ijse.rmi.cab.controller.ReservationController;
import lk.ijse.rmi.cab.controller.VehicleController;
import lk.ijse.rmi.cab.dto.CustomerDTO;
import lk.ijse.rmi.cab.dto.InsuaranceCompanyDTO;
import lk.ijse.rmi.cab.dto.ReservationDTO;
import lk.ijse.rmi.cab.dto.VehicleDTO;
import lk.ijse.rmi.cab.observer.Observer;

/**
 *
 * @author user
 */
public class VehicleReserveForm extends javax.swing.JPanel implements Observer{
   
    /**
     * Creates new form VehicleReserveForm
     */
    public VehicleReserveForm() throws RemoteException{
       
        try {
            initComponents();
            UnicastRemoteObject.exportObject(this, 0);
            
            ReservationController.registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    VehicleReserveForm(String startDate, String endDate, int vehicleId, String vehicleBrand, String vehicleInsuaranceId, String vehicleRegNum, String vehicleColour, int vehicleSeatinCapacity, String vehicleFuelType, String vehicleStatus, Double vehiclePrice, String vehicleInsuaranceCompanyId) {
         initComponents();
         btnPayment.setEnabled(false);
         txtVehicleInsuaranceCompanyId1.requestFocus();
         txtStartDate.setText(startDate);
         txtEndDate.setText(endDate);
         txtPrice.setText(vehiclePrice+"");
         
         txtVehicleId.setText(vehicleId+"");
         txtVehicleBrand.setText(vehicleBrand);
         txtVehicleInsuaranceId.setText(vehicleInsuaranceId);
         txtVehicleRegNo.setText(vehicleRegNum);
         txtVehicleColour.setText(vehicleColour);
         txtVehicleSeatingCapacity.setText(vehicleSeatinCapacity+"");
         txtVehicleFuelType.setText(vehicleFuelType);
         txtVehicleStatus.setText(vehicleStatus);
         txtVehiclePrice.setText(vehiclePrice+"");
         txtVehicleInsuaranceCompanyId1.setText(vehicleInsuaranceCompanyId);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCustNicNumber = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtCustId = new javax.swing.JTextField();
        txtCustDOB = new javax.swing.JTextField();
        txtCustTelNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        txtVehicleBrand = new javax.swing.JTextField();
        txtVehicleInsuaranceId = new javax.swing.JTextField();
        txtVehicleSeatingCapacity = new javax.swing.JTextField();
        txtVehicleFuelType = new javax.swing.JTextField();
        txtVehicleColour = new javax.swing.JTextField();
        txtVehicleRegNo = new javax.swing.JTextField();
        txtVehiclePrice = new javax.swing.JTextField();
        txtVehicleStatus = new javax.swing.JTextField();
        txtInsuaranceCompanyType = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCustomerLicenceId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtVehicleInsuaranceCompanyId1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtInsuaranceCompanyName = new javax.swing.JTextField();
        btnAddNewCustomer = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtReservationId = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(150, 40, 27));
        setPreferredSize(new java.awt.Dimension(1564, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/vehicle.png"))); // NOI18N
        jLabel1.setText(" Vehicle Reserve");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/user.png"))); // NOI18N
        jLabel2.setText(" Customer Details");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("NIC_Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Cust_Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Cust_Id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Cust_DOB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Cust_Licence_Id");

        txtCustNicNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCustNicNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNicNumberActionPerformed(evt);
            }
        });

        txtCustName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustDOB.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtCustTelNumber.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/vehicle.png"))); // NOI18N
        jLabel8.setText("  Vehicle Details");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Start _Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Price");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("End_Date");

        txtStartDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtEndDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/reservation.png"))); // NOI18N
        jLabel12.setText("  Reseve Detail");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setRequestFocusEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setText("Vehicle _ID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Vehicle_Insurance_ID");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Vehicle_Reg_No");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Vehicle_Seating_Capaciy ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 255));
        jLabel17.setText("Vehicle_Brand");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 102, 255));
        jLabel18.setText("Vehicle _FuelType");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 255));
        jLabel19.setText("Vehicle _Status");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 102, 255));
        jLabel20.setText("Vehicle_Price");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 102, 255));
        jLabel21.setText("Insurnce_company_Type");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 102, 255));
        jLabel22.setText("Vehicle_Colour");

        txtVehicleId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehicleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdActionPerformed(evt);
            }
        });

        txtVehicleBrand.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleInsuaranceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleSeatingCapacity.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleFuelType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleColour.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehicleRegNo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtVehiclePrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehiclePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiclePriceActionPerformed(evt);
            }
        });

        txtVehicleStatus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txtInsuaranceCompanyType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 102, 255));
        jLabel23.setText("Cust_Tel_Num");

        txtCustomerLicenceId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 102, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/reservation.png"))); // NOI18N
        btnSave.setText("Reserve");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 255));
        jLabel24.setText(" Vehicle_Insrnce_Company_Id");

        txtVehicleInsuaranceCompanyId1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtVehicleInsuaranceCompanyId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleInsuaranceCompanyId1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 102, 255));
        jLabel25.setText("Insurnce_company_Name");

        txtInsuaranceCompanyName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btnAddNewCustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewCustomer.setForeground(new java.awt.Color(102, 102, 255));
        btnAddNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/addReciption.png"))); // NOI18N
        btnAddNewCustomer.setText("Add New Customer");
        btnAddNewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewCustomerMouseClicked(evt);
            }
        });
        btnAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCustomerActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 102, 255));
        jLabel26.setText("Reservation_ID");

        txtReservationId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(51, 102, 255));
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/rmi/cab/resource/payment.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCustomerLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnAddNewCustomer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                .addComponent(txtPrice))
                                            .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPayment)
                                .addGap(29, 29, 29)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVehicleInsuaranceCompanyId1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVehicleInsuaranceId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtInsuaranceCompanyType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(54, 54, 54)
                                        .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtVehicleSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustNicNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerLicenceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPayment)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddNewCustomer)
                                .addComponent(btnSave))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVehicleInsuaranceCompanyId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsuaranceCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVehicleInsuaranceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtInsuaranceCompanyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNicNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNicNumberActionPerformed
        String nic=txtCustNicNumber.getText();
        if (nic.matches("[0-9]{9}[vV]")){
            //JOptionPane.showMessageDialog(this, "Valid NIC");
        }else{
            JOptionPane.showMessageDialog(this, "Invalid NIC");
        }
        try {
            String nicNumber=txtCustNicNumber.getText();
            CustomerDTO customerDTO=CustomerController.findBYNicNumber(nicNumber);
            if(customerDTO!=null){
                txtCustId.setText(customerDTO.getCustId()+"");
                txtCustName.setText(customerDTO.getCustName());
                txtCustomerLicenceId.setText(customerDTO.getCustLicenseId());
                txtCustTelNumber.setText(customerDTO.getCustTelNumber());
                txtCustDOB.setText(customerDTO.getCustDob());
                
            }else{
                JOptionPane.showMessageDialog(this,"No Such Customer");
            }
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCustNicNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        try {
            VehicleDTO vehicleDTO=new VehicleDTO();
            vehicleDTO.setVehicleId(Integer.parseInt(txtVehicleId.getText()));
            vehicleDTO.setVehicleBrand(txtVehicleBrand.getText());
            vehicleDTO.setVehicleInsuaranceId(txtVehicleInsuaranceId.getText());
            vehicleDTO.setRegNo(txtVehicleRegNo.getText());
            vehicleDTO.setColour(txtVehicleColour.getText());
            vehicleDTO.setSeatingCapacity(Integer.parseInt(txtVehicleSeatingCapacity.getText()));
            vehicleDTO.setFuelType(txtVehicleFuelType.getText());
            vehicleDTO.setStatus(txtVehicleStatus.getText());
            vehicleDTO.setPrice(Double.parseDouble(txtVehiclePrice.getText()));
            
            InsuaranceCompanyDTO insuaranceCompanyDTO=new InsuaranceCompanyDTO();
            insuaranceCompanyDTO.setInsuaranceCompanyId(txtVehicleInsuaranceCompanyId1.getText());
            insuaranceCompanyDTO.setCompanyName(txtInsuaranceCompanyName.getText());
           insuaranceCompanyDTO.setInsuaranceType(txtInsuaranceCompanyType.getText());
            vehicleDTO.setInsuaranceCompanyDTO(insuaranceCompanyDTO);
            
            CustomerDTO customerDTO=new CustomerDTO();
            customerDTO.setCustId(Integer.parseInt(txtCustId.getText()));
            customerDTO.setCustName(txtCustName.getText());
            customerDTO.setCustNic(txtCustNicNumber.getText());
            customerDTO.setCustLicenseId(txtCustomerLicenceId.getText());
            customerDTO.setCustTelNumber(txtCustTelNumber.getText());
            customerDTO.setCustDob(txtCustDOB.getText());
            
            ReservationDTO reservationDTO=new ReservationDTO();
            reservationDTO.setReseveId(txtReservationId.getText());
            reservationDTO.setStartDate(txtStartDate.getText());
            reservationDTO.setEndDate(txtEndDate.getText());
            reservationDTO.setPrice(Double.parseDouble(txtPrice.getText()));
            reservationDTO.setCustomerDTO(customerDTO);
            reservationDTO.setVehicleDTO(vehicleDTO);
            
            boolean isAdded=ReservationController.addReservation(reservationDTO);
            if(isAdded){
                ReservationController.releaseReservation(Integer.parseInt(txtVehicleId.getText()));
                JOptionPane.showMessageDialog(this,"Added");
                btnPayment.setEnabled(true);
                
                btnPayment.setForeground(Color.green);
                btnPayment.setText("press Payment Button");
            }else{
                JOptionPane.showMessageDialog(this,"Not Added");
                 JOptionPane.showMessageDialog(this, "Please Fill Press Reseve Button");
                btnPayment.setForeground(Color.red);
                btnPayment.setText("Wrong Data");
                btnPayment.setEnabled(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtVehicleInsuaranceCompanyId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleInsuaranceCompanyId1ActionPerformed
        try {
            String id=txtVehicleInsuaranceCompanyId1.getText();
            InsuaranceCompanyDTO insuaranceCompanyDTO=InsuaranceCompanyController.searchById(id);
            if(insuaranceCompanyDTO!=null){
                txtInsuaranceCompanyName.setText(insuaranceCompanyDTO.getCompanyName());
                txtInsuaranceCompanyType.setText(insuaranceCompanyDTO.getInsuaranceType());
            }
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtVehicleInsuaranceCompanyId1ActionPerformed

    private void txtVehiclePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiclePriceActionPerformed
       
    }//GEN-LAST:event_txtVehiclePriceActionPerformed

    private void btnAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCustomerActionPerformed
       

        
    }//GEN-LAST:event_btnAddNewCustomerActionPerformed

    private void btnAddNewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewCustomerMouseClicked
        int vehicleId=Integer.parseInt(txtVehicleId.getText());
        String startDate=txtStartDate.getText();
        String endDate=txtEndDate.getText();
        Double price=Double.parseDouble(txtPrice.getText());
        String vehicleBrand=txtVehicleBrand.getText();
        String vehicleInsuaranceId=txtVehicleInsuaranceId.getText();
        String vehicleRegNumber=txtVehicleRegNo.getText();
        String vehiclcolour=txtVehicleColour.getText();
        int vehicleSeatingCapacity=Integer.parseInt(txtVehicleSeatingCapacity.getText());
        String vehicleFuelType=txtVehicleFuelType.getText();
        String vehicleStatus=txtVehicleStatus.getText();
        Double vehiclePrice=Double.parseDouble(txtVehiclePrice.getText());
        String vehicleInsuaranceCompanyID=txtVehicleInsuaranceCompanyId1.getText();
        String vehicleInsuaranceCompanyName=txtInsuaranceCompanyName.getText();
        String vehicleInsuaranceCompanyType=txtInsuaranceCompanyType.getText();
        
        AddNewCustomer addNewCustomer=new AddNewCustomer(vehicleId,startDate,endDate,price,vehicleBrand,vehicleInsuaranceId,
        vehicleRegNumber,vehiclcolour,vehicleSeatingCapacity,vehicleFuelType,vehicleStatus,vehicleInsuaranceCompanyID,vehiclePrice,
        vehicleInsuaranceCompanyName,vehicleInsuaranceCompanyType);
        
        
        addNewCustomer.setSize(this.getSize());
        this.removeAll();
        this.add(addNewCustomer);
        this.repaint();
        this.revalidate();
        addNewCustomer.setVisible(true);
    }//GEN-LAST:event_btnAddNewCustomerMouseClicked

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        String ReservationId=txtReservationId.getText();
        String checkIn = txtStartDate.getText();
        String checkOut = txtEndDate.getText();
        //String custId=txtCustId.getText()+"";
        int vehicleId=Integer.parseInt(txtVehicleId.getText());
        
        String custName=txtCustName.getText();
        String custNic=txtCustNicNumber.getText();
        String custLicenId=txtCustomerLicenceId.getText();
        String custTel=txtCustTelNumber.getText();
        String custDOB=txtCustDOB.getText();
        
        String vehicleBrand=txtVehicleBrand.getText();
        String vehicleInsuaranceId=txtVehicleInsuaranceId.getText();
        String vehicleRegNumber=txtVehicleRegNo.getText();
        String vehiclcolour=txtVehicleColour.getText();
        int vehicleSeatingCapacity=Integer.parseInt(txtVehicleSeatingCapacity.getText());
        String vehicleFuelType=txtVehicleFuelType.getText();
        String vehicleStatus=txtVehicleStatus.getText();
        Double vehiclePrice=Double.parseDouble(txtVehiclePrice.getText());
        String vehicleInsuaranceCompanyID=txtVehicleInsuaranceCompanyId1.getText();
        String vehicleInsuaranceCompanyName=txtInsuaranceCompanyName.getText();
        String vehicleInsuaranceCompanyType=txtInsuaranceCompanyType.getText();
        
        
        
        
        AdvancePaymentForm advancePaymentForm=new AdvancePaymentForm(ReservationId, checkIn,checkOut,vehicleId,custName,custNic,custLicenId,
        custTel,custDOB,vehicleBrand,vehicleInsuaranceId,vehicleRegNumber,vehiclcolour,vehicleSeatingCapacity,vehicleFuelType,
        vehicleStatus,vehiclePrice,vehicleInsuaranceCompanyID,vehicleInsuaranceCompanyName,vehicleInsuaranceCompanyType);
        
        advancePaymentForm.setSize(this.getSize());
        this.removeAll();
        this.add(advancePaymentForm);
        this.repaint();
        this.revalidate();
        advancePaymentForm.setVisible(true);
        
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void txtVehicleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdActionPerformed
        
        try {
            int vehicleId=Integer.parseInt(txtVehicleId.getText());
            
            VehicleDTO vehicleDTO=VehicleController.findVehicle(vehicleId);
            if(vehicleDTO!=null){
                boolean reseved=ReservationController.reserveReservation(vehicleId);
                if(reseved){
                    txtVehicleId.setText(vehicleDTO.getVehicleId()+"");
                    txtVehicleBrand.setText(vehicleDTO.getVehicleBrand());
                    txtVehicleInsuaranceId.setText(vehicleDTO.getVehicleInsuaranceId());
                    txtVehicleRegNo.setText(vehicleDTO.getRegNo());
                    txtVehicleColour.setText(vehicleDTO.getColour());
                    txtVehicleSeatingCapacity.setText(vehicleDTO.getSeatingCapacity()+"");
                    txtVehicleFuelType.setText(vehicleDTO.getFuelType());
                    txtVehicleStatus.setText(vehicleDTO.getStatus());
                    txtVehiclePrice.setText(vehicleDTO.getPrice()+"");
                    txtVehicleInsuaranceCompanyId1.setText(vehicleDTO.getInsuaranceCompanyDTO().getInsuaranceCompanyId());
                }else{
                    JOptionPane.showMessageDialog(this,"while reserving");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(VehicleReserveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
            
          
         
    }//GEN-LAST:event_txtVehicleIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCustomer;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCustDOB;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustNicNumber;
    private javax.swing.JTextField txtCustTelNumber;
    private javax.swing.JTextField txtCustomerLicenceId;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtInsuaranceCompanyName;
    private javax.swing.JTextField txtInsuaranceCompanyType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReservationId;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtVehicleBrand;
    private javax.swing.JTextField txtVehicleColour;
    private javax.swing.JTextField txtVehicleFuelType;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtVehicleInsuaranceCompanyId1;
    private javax.swing.JTextField txtVehicleInsuaranceId;
    private javax.swing.JTextField txtVehiclePrice;
    private javax.swing.JTextField txtVehicleRegNo;
    private javax.swing.JTextField txtVehicleSeatingCapacity;
    private javax.swing.JTextField txtVehicleStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String message) throws Exception {
        JOptionPane.showMessageDialog(this,message);
    }
}
